name: CI

on:
  push:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  bandit_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install Bandit
        run: |
          pip install bandit
          pip install bandit-sarif-formatter

      - name: Run Bandit Scan
        run: |
          bandit -r . -f sarif -o bandit-report.sarif -ll -ii || true

      - name: Upload Bandit SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: bandit-report.sarif
          category: bandit

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-findings
          path: bandit-report.json

  build_image:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Build Docker Image
        run: docker build -f Dockerfile -t myapp:latest .


      - name: Docker Scout Scan
        uses: docker/scout-action@v1.11.0
        with:
          dockerhub-user: ${{ secrets.REPO_USER }}
          dockerhub-password: ${{ secrets.REPO_PWD }}
          command: quickview,cves
          only-severities: critical,high
          sarif-file: scout-report.sarif

      - name: Upload Docker Scout SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: scout-report.sarif
          category: docker-scout
        

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docker-scout-findings
          path: scout-report.sarif

  semgrep_scan:
    name: Run Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Run Semgrep
        run: semgrep scan --severity=ERROR --severity WARNING --sarif --output=sast-semgrep.sarif || true 

      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: sast-semgrep.sarif
          category: semgrep

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: semgrep-findings
          path: sast-semgrep.sarif